name: SimplePipeline

on:
  push:
    branches: [master]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint
        env:
          CI: true

  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Vulnerabilities
        run: npm audit --audit-level=moderate

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test:unit
      - name: Run Integration Tests
        run: npm run test:e2e

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [lintTest, securityCheck, test]
    steps:
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy to Server
        run: |
          echo "Deployment in progress..."
          # Add deployment script or command (e.g., Docker, SSH, or cloud provider CLI)
