name: SimplePipline

on:
  push:
    branches: [master]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies..."
          npm install
      - name: Run Linting
        run: |
          echo "Running Linting ..."
          npm run lint
        env:
          CI: true
  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Check ..."
          sleep 5s;

          echo "Running Security Check ... 1"
          sleep 5s;

          echo "Running Security Check ... 2"
          sleep 5s;
  deploye:
    name: Deployement
    runs-on: ubuntu-latest
    needs: [lintTest, securityCheck]
    steps:
      - name: Install Dependencies
        run: |
          echo "Deployement in progress..."
